### PR TITLE
Add startup script to improve startup command

### PR DESCRIPTION
**Pull request by wshino**
This PR improves starting relayer docker container.
I've added startup.sh, and then docker run command executes this script.
We don't have to do docker exec to start up a process no longer.

In addition, I've updated the README.md, we can inject .env file into docker container inside.

In checking the behavior, in my local environment, there are some errors at `cargo run --release -- setup`
I guess it's my setup is wrong.
For reviewers could you please check the behavior if you have time.

```
Error: Contract call reverted with data: 0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000001a72656c6179657220616c72656164792072656769737465726564000000000000
Error: Failed to run cargo run --release -- setup
```

### CODE REVIEW

**Comment by SoraSuegami** [comment]
Sorry for the late review!

> For reviewers could you please check the behavior if you have time.
> Error: Contract call reverted with data: 0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000001a72656c6179657220616c72656164792072656769737465726564000000000000

This error message means "relayer already registered".
Did you use a new relayer's ethereum address?

**Comment by wshino** [comment]
> Sorry for the late review!
> 
> > For reviewers could you please check the behavior if you have time.
> > Error: Contract call reverted with data: 0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000001a72656c6179657220616c72656164792072656769737465726564000000000000
> 
> This error message means "relayer already registered". Did you use a new relayer's ethereum address?

Thanks Sora-san, actually I used the same `.env` in relayer-v1, that's the reason.

I can do the following steps to avoid this, is that okay?

1. build a new image use the same command with [README.md](https://github.com/zkemail/email-wallet/pull/38/files#diff-d31fb0423fc8a1fca30ec0acf18dea0d1ac04011606ae43959c67b1f96222dddR119) 
2. Change PRIVATE_KEY in .env
3. docker run

I have one concern about the above steps, if the above step is correct, Maybe I shouldn't do docker runs locally, because if I use the same address in production, it will cause a relayer already registered. And also we will consume not needed gas fee to register the address to the contract. 

Maybe `cargo run --release -- setup` is not needed in startup.sh. In that case, should I use a different argument to start the docker image?

**Comment by SoraSuegami** [comment]
> Maybe cargo run --release -- setup is not needed in startup.sh. In that case, should I use a different argument to start the docker image?

Yes, we can assume the relayer already runs the setup and remove the `cargo run --release -- setup` from the startup.sh.
I think you only need to do `cargo run --release`, but please let me know if you have any errors.

**Comment by SoraSuegami** [comment]
Could you solve the conflict at `packages/relayer/README.md`?

**Comment by wshino** [comment]
> Could you solve the conflict at `packages/relayer/README.md`?

Sorry for late reply, I've just fixed the conflict.

**Review by saleel — APPROVED** [review]

**Comment by SoraSuegami** [comment]
@wshino 
Could you merge the main branch again and ensure that the unit tests pass?

**Comment by wshino** [comment]
@SoraSuegami oh it's already merged. Let me check main branch unit testing.

**Comment by wshino** [comment]
@SoraSuegami sure let me check

**Comment by saleel** [comment]
> @SoraSuegami sure let me check

Ah yea I merged main here to see if the tests passed. I think everything is fine here now.
Merging.

**Pull request merged**
