### PR TITLE
feat: Merge NFT Demo branch

### PR DESCRIPTION
**Pull request by Bisht13**

### CODE REVIEW

**Comment by SoraSuegami** [comment]
https://github.com/zkemail/email-wallet/blob/feat/merge-nft-demo/packages/circuits/scripts/account_creation.ts#L11
I think you missed the circuits/helpers directory.

**Comment by Bisht13** [comment]
> https://github.com/zkemail/email-wallet/blob/feat/merge-nft-demo/packages/circuits/scripts/account_creation.ts#L11 I think you missed the circuits/helpers directory.

I removed it since it was no longer needed to be called from the relayer.

**Comment by SoraSuegami** [comment]
I understand.
However, its codes are imported in the circuit tests.
Could you make alternative functions to generate inputs for each circuit in the utils package and call them in the circuit tests?

**Comment by Bisht13** [comment]
> I understand. However, its codes are imported in the circuit tests. Could you make alternative functions to generate inputs for each circuit in the utils package and call them in the circuit tests?

I understand, so do you mean to expose the rust functions for circuit inputs as wasm bindings and use them to pass the tests?

**Comment by SoraSuegami** [comment]
Yes, but instead of exposing the functions as wasm, you can expose them as nodejs functions as neon. Please refer to the functions with the suffix "node" and the lib.rs in the utils package to know how to do that.

**Comment by Bisht13** [comment]
> Yes, but instead of exposing the functions as wasm, you can expose them as nodejs functions as neon. Please refer to the functions with the suffix "node" and the lib.rs in the utils package to know how to do that.

Sure, I'll expose them via neon and pass the tests.

**Pull request merged**
